name: NautyTracesInterface
version: "0.2"
date: 2018-03-01
description: |
    An interface to nauty

authors:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Alice Niemeyer
      url: http://www.maths.uwa.edu.au/~alice/
    - name: Pascal Schweitzer
      url: https://lii.rwth-aachen.de/~schweitzer

maintainers:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io
    - name: Alice Niemeyer
      url: http://www.maths.uwa.edu.au/~alice/
    - name: Pascal Schweitzer
      url: https://lii.rwth-aachen.de/~schweitzer

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://TODO/
readme: README.md
packageinfo: http://TODO/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://TODO/NautyTracesInterface-0.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GNS18</span>]   <b class='BibAuthor'>Gutsche, S., Niemeyer, A. and Schweitzer, P.</b>,
     <i class='BibTitle'>NautyTracesInterface, An interface to nauty,
             Version 0.2</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="http://TODO/">http://TODO/</a></span>.
    </p>
    

bibtex: |
    @misc{ NautyTracesInterface0.2,
      author =           {Gutsche, S. and Niemeyer, A. and Schweitzer, P.},
      title =            {{NautyTracesInterface}, An interface to nauty, {V}ersion 0.2},
      month =            {Mar},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href {http://TODO/} {\texttt{http://TODO/}}},
      printedkey =       {GNS18}
    }

