name: NautyTracesInterface
version: "0.2"
date: 2018-03-01
description: |
    An interface to nauty

authors:
    - name: Sebastian Gutsche
      url: https://sebasguts.github.io

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.11"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/NautyTracesInterface/
readme: README.md
packageinfo: https://gap-packages.github.io/NautyTracesInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/NautyTracesInterface/releases/download/v0.2/NautyTracesInterface-0.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GT18</span>]   <b class='BibAuthor'>Gutsche, S. and GAP Team, T.</b>,
     <i class='BibTitle'>NautyTracesInterface, An interface to nauty,
             Version 0.2</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/NautyTracesInterface/">https://gap-packages.github.io/NautyTracesInterface/</a></span>.
    </p>
    

bibtex: |
    @misc{ NautyTracesInterface0.2,
      author =           {Gutsche, S. and GAP Team, T.},
      title =            {{NautyTracesInterface}, An interface to nauty, {V}ersion 0.2},
      month =            {Mar},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href                {https://gap-packages.github.io/NautyTracesInterface/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{NautyTracesInterface/}}},
      printedkey =       {GT18}
    }

